services:
  - type: web
    name: esugo
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py load_initial_data_once && python manage.py create_admin_once
    startCommand: gunicorn Esugo.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: esugo-db
          property: connectionString
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_PUBLIC_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: krixiesarong9@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: esugo-db
