# Generated by Codex on 2026-05-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_order_rider_alter_order_user_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Esugo Grocery', max_length=150)),
                ('location', models.TextField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('rider', 'Rider'), ('store_owner', 'Store Owner')], default='customer', max_length=20),
        ),
    ]
