# Generated by Django 6.0.3 on 2026-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymongo_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
